_target_: src.models.CodeClassificationCNN
embedding_dim: 32
num_classes: 54
hidden_dims:
  - 128
kernel_sizes: [5]
padding_idx: ${padding_idx}
vocab_size: ${vocab_size}
block: 
  _target_: src.models.ConvNormActPool
  _partial_: true
